### ISSUE TITLE
struggling to run the app

### ISSUE THREAD

**Issue by aiqbal69** [prine/ROGoogleTranslate#3]
Hi i downloaded the project and followed the instructions provided. My understanding of the instructions was to just insert my own api key and then compile the app and then insert the text that is to be translated  into the textfield and the app should work, so i went into google translate console and obtained the google translate api and had enabled the api. I inserted the api within the code. When i run the app and type in the text to translate and then press the 'translate' button. I get the following output. 
"2017-02-25 22:38:40.667724 ROGoogleTranslate[18027:1355532] [] nw_host_stats_add_src recv too small, received 24, expected 28
2017-02-25 22:38:40.675490 ROGoogleTranslate[18027:1355532] [] ____nwlog_simulate_crash_inner_block_invoke dlopen CrashReporterSupport failed
2017-02-25 22:38:40.676338 ROGoogleTranslate[18027:1355532] [] __nwlog_err_simulate_crash simulate crash failed "nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available"
2017-02-25 22:38:40.678888 ROGoogleTranslate[18027:1355532] [] nw_socket_set_common_sockopts setsockopt SO_NOAPNFALLBK failed: [42] Protocol not available, dumping backtrace"

I also get the following error each time i click the translate button
'Response [403] - 230 bytes'
I tried googling the errors but got no luck!
I have posted the issue on stack overflow  [http://stackoverflow.com/questions/42449468/implementing-google-translation-api-in-swift-3-ios](url)
Is this an error with the code or is it with it my api key, or do i need to alter the code more in order for the app to work. 
ThankYou

**Comment by prine** [comment]
I guess you get the 403 because your Google Api Account is not yet activated correctly. Google has changed the policy of the Translation api and its not free anymore. So you problably didn't add the credit card informations in the Api account?

The other warnings above is unfortunately from the core libraries from Swift. You can turn this warnings of with the setting in the running scheme "OS_ACTIVITY_MODE" to "disable". (Further info you find here: https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-8-logs).
